#include "RCC.h"
void RCC_GPIOA_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_IOPA;
}
void RCC_GPIOB_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_IOPB;
}
void RCC_GPIOC_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_IOPC;
}
void RCC_GPIOD_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_IOPD;
}
void RCC_GPIOE_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_IOPE;
}
void RCC_TIM2_EnableClock(void){
	RCC->RCC_APB1ENR |= RCC_APB1ENR_TIM2;
}
void RCC_ADC1_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_ADC1;
}
void RCC_I2C1_EnableClock(void){
	RCC->APB1RSTR |= RCC_APB1ENR_I2C1;
}
void RCC_UART1_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_UART1;
}
void RCC_AFIO_EnableClock(void){
	RCC->RCC_APB2ENR |= RCC_APB2ENR_AFIO;
	
}
void RCC_SetSysCLK_72MHz(void){
	RCC->RCC_CR |= RCC_CR_HSEON; // HSE ON
	while((RCC->RCC_CR&RCC_CR_HSERDY)==0){
		// wait HSE ready
	}
	
	RCC->RCC_CFGR &= ~RCC_CFGR_PLLXTPRE_MASK;
  RCC->RCC_CFGR |=  RCC_CFGR_PLLXTPRE_HSE_DIV1;
	
	ACR &= ~(FLASH_ACR_LATENCY_MASK);
	ACR |= FLASH_ACR_LATENCY2;
	ACR |= FLASH_ACR_PRFTBE;
	
	RCC->RCC_CFGR &= ~RCC_CFGR_HPRE_MASK;
	RCC->RCC_CFGR |= RCC_CFGR_HPRE_DIV1;
	
	RCC->RCC_CFGR &= ~RCC_CFGR_PPRE1_MASK;
	RCC->RCC_CFGR |= RCC_CFGR_PPRE1_HCLK_DIV2;
	
	RCC->RCC_CFGR &= ~RCC_CFGR_PPRE2_MASK;
	RCC->RCC_CFGR |= RCC_CFGR_PPRE2_HCLK_DIV1;
	
	RCC->RCC_CFGR &= ~RCC_CFGR_PLLSRC_MASK;
	RCC->RCC_CFGR |= RCC_CFGR_PLLSRC_HSE;
	
	RCC->RCC_CFGR &= ~RCC_CFGR_PLLMUL_MASK;
	RCC->RCC_CFGR |= RCC_CFGR_PLLMUL_x9;
	
	RCC->RCC_CR |= RCC_CR_PLLON;
	while((RCC->RCC_CR&RCC_CR_PLLRDY)==0){
	}
	
	RCC->RCC_CFGR &= ~RCC_CFGR_SW_MASK;
	RCC->RCC_CFGR |= RCC_CFGR_SW_PLL;
	while((RCC->RCC_CFGR&RCC_CFGR_SWS_MASK)!=RCC_CFGR_SWS_PLL){
		
	}
	
}